package store

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"net/netip"
	"strings"
)

// WGSite is a WireGuard site: a plain WireGuard peer that fronts remote
// networks, so an upstream can be reached "via" it (SPEC-wireguard.md part 1).
type WGSite struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	PublicKey string `json:"publicKey"` // base64; the private key never reaches quicgate
	// PresharedKey is generated by quicgate, sealed at rest, and returned by
	// the API exactly once, when the site is created.
	PresharedKey string   `json:"presharedKey,omitempty"`
	Address      string   `json:"address"`  // the site's /32 in the tunnel network; assigned, never chosen
	Networks     []string `json:"networks"` // remote IPv4 prefixes behind the site
	Endpoint     string   `json:"endpoint"` // host:port when quicgate can call the site; empty when it dials in
	Keepalive    int      `json:"keepalive"`
	Enabled      bool     `json:"enabled"`
	// AllowOwnOverlap confirms that one of Networks overlaps a network this
	// machine is on. Traffic only enters the tunnel for upstreams that name the
	// site, so nothing local is captured, but the operator should mean it.
	AllowOwnOverlap bool   `json:"allowOwnOverlap,omitempty"`
	CreatedAt       string `json:"createdAt,omitempty"`
	UpdatedAt       string `json:"updatedAt,omitempty"`
}

func wgSitePSKAAD(id int64) string { return aad("wg_sites", "psk", id) }

func (s *Store) migrateWG() error {
	_, err := s.db.Exec(`CREATE TABLE IF NOT EXISTS wg_sites (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL COLLATE NOCASE,
  public_key TEXT UNIQUE NOT NULL,
  psk TEXT NOT NULL DEFAULT '',
  address TEXT UNIQUE NOT NULL,
  networks TEXT NOT NULL DEFAULT '[]',
  endpoint TEXT NOT NULL DEFAULT '',
  keepalive INTEGER NOT NULL DEFAULT 25,
  enabled INTEGER NOT NULL DEFAULT 1,
  allow_own_overlap INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);`)
	return err
}

const wgSiteCols = "id, name, public_key, psk, address, networks, endpoint, keepalive, enabled, allow_own_overlap, created_at, updated_at"

// scanWGSite reads a site and opens its preshared key. A key that cannot be
// opened (locked store) makes the site unusable, which the caller sees as an
// empty PresharedKey: the engine then leaves the site out instead of
// configuring a peer with the wrong key.
func (s *Store) scanWGSite(row interface{ Scan(...any) error }) (WGSite, error) {
	var w WGSite
	var networks, psk string
	var enabled, overlap int
	if err := row.Scan(&w.ID, &w.Name, &w.PublicKey, &psk, &w.Address, &networks, &w.Endpoint, &w.Keepalive, &enabled, &overlap, &w.CreatedAt, &w.UpdatedAt); err != nil {
		return w, err
	}
	if err := json.Unmarshal([]byte(networks), &w.Networks); err != nil {
		return w, fmt.Errorf("site %d: networks: %w", w.ID, err)
	}
	w.Enabled, w.AllowOwnOverlap = enabled == 1, overlap == 1
	if plain, err := s.openSecret(psk, wgSitePSKAAD(w.ID)); err == nil {
		w.PresharedKey = plain
	}
	return w, nil
}

// ListWGSites returns every site, with its preshared key: for the engine.
// The admin API blanks the key before it answers.
func (s *Store) ListWGSites() ([]WGSite, error) {
	rows, err := s.db.Query("SELECT " + wgSiteCols + " FROM wg_sites ORDER BY name")
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []WGSite{}
	for rows.Next() {
		w, err := s.scanWGSite(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, w)
	}
	return out, rows.Err()
}

func (s *Store) GetWGSite(id int64) (WGSite, error) {
	return s.scanWGSite(s.db.QueryRow("SELECT "+wgSiteCols+" FROM wg_sites WHERE id=?", id))
}

// nextWGAddress returns the lowest free host address of the tunnel network,
// after quicgate's own (the first). When an address comes back into use for
// another site, the engine rebuilds its network stack first: no address
// changes owner inside a running stack instance.
func nextWGAddress(q dbtx, tunnel netip.Prefix) (netip.Addr, error) {
	// Sites and devices share the tunnel network. A revoked device has no
	// address any more.
	rows, err := q.Query("SELECT address FROM wg_sites UNION ALL SELECT address FROM wg_devices WHERE address IS NOT NULL")
	if err != nil {
		return netip.Addr{}, err
	}
	defer rows.Close()
	used := map[netip.Addr]bool{}
	for rows.Next() {
		var a string
		if err := rows.Scan(&a); err != nil {
			return netip.Addr{}, err
		}
		if ip, err := netip.ParseAddr(a); err == nil {
			used[ip] = true
		}
	}
	tunnel = tunnel.Masked()
	last := lastAddr(tunnel)
	for a := tunnel.Addr().Next().Next(); tunnel.Contains(a) && a != last; a = a.Next() {
		if !used[a] {
			return a, nil
		}
	}
	return netip.Addr{}, fmt.Errorf("the tunnel network %s has no free address left", tunnel)
}

// lastAddr is the broadcast address of an IPv4 prefix.
func lastAddr(p netip.Prefix) netip.Addr {
	b := p.Masked().Addr().As4()
	host := 32 - p.Bits()
	for i := 0; i < host; i++ {
		b[3-i/8] |= 1 << (i % 8)
	}
	return netip.AddrFrom4(b)
}

// CreateWGSite stores a new site. The address is assigned here; psk is the
// preshared key to seal. Validation of keys and networks is the caller's job
// (wg.ValidateSite): it needs the server key and this machine's networks.
func (s *Store) CreateWGSite(w *WGSite, tunnel netip.Prefix, psk string) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	var devices int
	if err := tx.QueryRow("SELECT COUNT(*) FROM wg_devices WHERE public_key=?", w.PublicKey).Scan(&devices); err != nil {
		return err
	}
	if devices > 0 {
		return errors.New("a device already uses this public key, or did before it was revoked")
	}
	addr, err := nextWGAddress(tx, tunnel)
	if err != nil {
		return err
	}
	networks, _ := json.Marshal(w.Networks)
	ts := now()
	res, err := tx.Exec("INSERT INTO wg_sites (name, public_key, psk, address, networks, endpoint, keepalive, enabled, allow_own_overlap, created_at, updated_at) VALUES (?,?,'',?,?,?,?,?,?,?,?)",
		strings.TrimSpace(w.Name), w.PublicKey, addr.String(), string(networks), w.Endpoint, w.Keepalive, b2i(w.Enabled), b2i(w.AllowOwnOverlap), ts, ts)
	if err != nil {
		return wgConstraint(err)
	}
	id, _ := res.LastInsertId()
	sealed, err := s.sealSecret(psk, wgSitePSKAAD(id))
	if err != nil {
		return err
	}
	if _, err := tx.Exec("UPDATE wg_sites SET psk=? WHERE id=?", sealed, id); err != nil {
		return err
	}
	if err := tx.Commit(); err != nil {
		return err
	}
	w.ID, w.Address, w.CreatedAt, w.UpdatedAt = id, addr.String(), ts, ts
	return nil
}

// UpdateWGSite changes everything but the address, which a site keeps for
// life, and the preshared key, which only changes with a new site.
func (s *Store) UpdateWGSite(w *WGSite) error {
	networks, _ := json.Marshal(w.Networks)
	w.UpdatedAt = now()
	res, err := s.db.Exec("UPDATE wg_sites SET name=?, public_key=?, networks=?, endpoint=?, keepalive=?, enabled=?, allow_own_overlap=?, updated_at=? WHERE id=?",
		strings.TrimSpace(w.Name), w.PublicKey, string(networks), w.Endpoint, w.Keepalive, b2i(w.Enabled), b2i(w.AllowOwnOverlap), w.UpdatedAt, w.ID)
	if err != nil {
		return wgConstraint(err)
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return sql.ErrNoRows
	}
	return nil
}

// ErrWGSiteInUse is returned when a site that upstreams or streams still name
// would be deleted: they would silently stop working.
var ErrWGSiteInUse = errors.New("the site is still used")

// DeleteWGSite removes a site that nothing reaches through any more.
func (s *Store) DeleteWGSite(id int64) error {
	users, err := s.wgSiteUsers(id)
	if err != nil {
		return err
	}
	if len(users) > 0 {
		return fmt.Errorf("%w by %s", ErrWGSiteInUse, strings.Join(users, ", "))
	}
	res, err := s.db.Exec("DELETE FROM wg_sites WHERE id=?", id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return sql.ErrNoRows
	}
	return nil
}

// wgSiteUsers names the hosts and streams that reach something via the site.
func (s *Store) wgSiteUsers(id int64) ([]string, error) {
	var users []string
	hosts, err := s.ListHosts()
	if err != nil {
		return nil, err
	}
	for _, h := range hosts {
		for _, v := range h.Vias() {
			if v == id {
				users = append(users, "host "+strings.Join(h.Domains, ","))
				break
			}
		}
	}
	streams, err := s.ListStreams()
	if err != nil {
		return nil, err
	}
	for _, st := range streams {
		if st.Via == id {
			users = append(users, fmt.Sprintf("stream %d", st.ListenPort))
		}
	}
	return users, nil
}

func wgConstraint(err error) error {
	msg := err.Error()
	switch {
	case strings.Contains(msg, "wg_sites.name"):
		return errors.New("a site with this name already exists")
	case strings.Contains(msg, "wg_sites.public_key"):
		return errors.New("a site with this public key already exists")
	}
	return err
}
